services:
  psql:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: no_pass
    ports:
      - "127.0.0.1:5436:5432"
    volumes:
      - pgdata-11:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  pgdata-11: